using System.Data;
using ITShop.Models;
using Microsoft.EntityFrameworkCore;

namespace ITShop.Helpers;

public static class DatabaseSchemaInitializer
{
    // ตรวจและปรับ schema หลักของระบบก่อนเริ่ม seed ข้อมูลตั้งต้นที่หลังบ้านต้องใช้
    public static void EnsureBrandSchema(Csi402dbContext db)
    {
        var connection = db.Database.GetDbConnection();
        var shouldClose = connection.State != ConnectionState.Open;

        if (shouldClose)
        {
            connection.Open();
        }

        try
        {
            ExecuteNonQuery(connection, @"
                CREATE TABLE IF NOT EXISTS brands (
                    brand_id INT NOT NULL AUTO_INCREMENT,
                    brand_name VARCHAR(100) NOT NULL,
                    logo_url VARCHAR(255) NULL,
                    PRIMARY KEY (brand_id),
                    UNIQUE KEY uq_brands_brand_name (brand_name)
                ) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;");

            if (!ColumnExists(connection, "brands", "logo_url"))
            {
                ExecuteNonQuery(connection, "ALTER TABLE brands ADD COLUMN logo_url VARCHAR(255) NULL AFTER brand_name;");
            }

            if (!ColumnExists(connection, "products", "brand_id"))
            {
                ExecuteNonQuery(connection, "ALTER TABLE products ADD COLUMN brand_id INT NULL AFTER category_id;");
            }

            if (!IndexExists(connection, "products", "brand_id"))
            {
                ExecuteNonQuery(connection, "ALTER TABLE products ADD INDEX brand_id (brand_id);");
            }

            if (!ForeignKeyExists(connection, "products", "products_ibfk_brand"))
            {
                ExecuteNonQuery(connection, "ALTER TABLE products ADD CONSTRAINT products_ibfk_brand FOREIGN KEY (brand_id) REFERENCES brands (brand_id);");
            }

            // เติมข้อมูลตั้งต้นและ schema เสริมที่ระบบหน้าร้านกับหลังบ้านพึ่งพา
            BrandLogoHelper.SeedDefaultBrands(db);
            EnsureCatalogCategories(db);
            SeedCatalogProducts(db);
            EnsureComsetPackageSeed(db);
            EnsureAuthorizationData(db);
            EnsurePromotionCouponSchema(connection);
            EnsureInvitePromotionSchema(connection);
            ClearAutoGeneratedBrandLogos(connection);
            BackfillProductBrands(connection);
            NormalizeProductSkus(connection);
        }
        finally
        {
            if (shouldClose)
            {
                connection.Close();
            }
        }
    }

    // ตรวจว่าตารางมีคอลัมน์ที่ต้องการแล้วหรือยัง
    private static bool ColumnExists(System.Data.Common.DbConnection connection, string tableName, string columnName)
    {
        return Exists(connection, @"
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = DATABASE()
              AND table_name = @tableName
              AND column_name = @columnName
            LIMIT 1;", ("@tableName", tableName), ("@columnName", columnName));
    }

    // ตรวจว่ามี index นี้อยู่ในตารางแล้วหรือยัง
    private static bool IndexExists(System.Data.Common.DbConnection connection, string tableName, string indexName)
    {
        return Exists(connection, @"
            SELECT 1
            FROM information_schema.statistics
            WHERE table_schema = DATABASE()
              AND table_name = @tableName
              AND index_name = @indexName
            LIMIT 1;", ("@tableName", tableName), ("@indexName", indexName));
    }

    // ตรวจว่ามี foreign key constraint ตามชื่อที่ต้องการหรือยัง
    private static bool ForeignKeyExists(System.Data.Common.DbConnection connection, string tableName, string constraintName)
    {
        return Exists(connection, @"
            SELECT 1
            FROM information_schema.table_constraints
            WHERE table_schema = DATABASE()
              AND table_name = @tableName
              AND constraint_type = 'FOREIGN KEY'
              AND constraint_name = @constraintName
            LIMIT 1;", ("@tableName", tableName), ("@constraintName", constraintName));
    }

    // helper กลางสำหรับ query แบบมีหรือไม่มีข้อมูลจาก information_schema
    private static bool Exists(System.Data.Common.DbConnection connection, string sql, params (string Name, object Value)[] parameters)
    {
        using var command = connection.CreateCommand();
        command.CommandText = sql;

        foreach (var parameterValue in parameters)
        {
            var parameter = command.CreateParameter();
            parameter.ParameterName = parameterValue.Name;
            parameter.Value = parameterValue.Value;
            command.Parameters.Add(parameter);
        }

        return command.ExecuteScalar() != null;
    }

    // รันคำสั่ง SQL ที่ไม่ต้องการผลลัพธ์กลับ เช่น CREATE, ALTER, UPDATE
    private static void ExecuteNonQuery(System.Data.Common.DbConnection connection, string sql)
    {
        using var command = connection.CreateCommand();
        command.CommandText = sql;
        command.ExecuteNonQuery();
    }

    // ทำ SKU ของสินค้าที่ขาดหรือรูปแบบไม่ถูกต้องให้กลับมาเป็นมาตรฐานเดียวกัน
    private static void NormalizeProductSkus(System.Data.Common.DbConnection connection)
    {
        ExecuteNonQuery(connection, @"
            UPDATE products
            SET sku = CONCAT('SKU', LPAD(product_id, 3, '0'))
            WHERE sku IS NULL
               OR TRIM(sku) = ''
               OR UPPER(TRIM(sku)) NOT REGEXP '^SKU[0-9]+$';");
    }

    // พยายามจับคู่ brand_id ให้สินค้าที่ชื่อมีคำของแบรนด์อยู่แต่ยังไม่ได้ผูกแบรนด์
    private static void BackfillProductBrands(System.Data.Common.DbConnection connection)
    {
        ExecuteNonQuery(connection, @"
            UPDATE products p
            JOIN brands b ON UPPER(TRIM(p.name)) LIKE CONCAT('%', UPPER(TRIM(b.brand_name)), '%')
            SET p.brand_id = b.brand_id
            WHERE p.brand_id IS NULL;");
    }

    // ล้างค่าโลโก้ที่เคยสร้างอัตโนมัติไว้เพื่อให้ระบบใช้ค่าปัจจุบันแทน
    private static void ClearAutoGeneratedBrandLogos(System.Data.Common.DbConnection connection)
    {
        ExecuteNonQuery(connection, @"
            UPDATE brands
            SET logo_url = NULL
            WHERE logo_url LIKE '/brand-logos/%';");
    }

    // เติมหมวดสินค้าหลักของร้านให้ครบก่อน seed สินค้า
    private static void EnsureCatalogCategories(Csi402dbContext db)
    {
        var requiredCategories = new[]
        {
            "CPU",
            "Graphics Card",
            "Mainboard",
            "RAM",
            "Storage",
            "Power Supply",
            "Cooling",
            "Case",
            "Monitor",
            "Laptop",
            "Mouse",
            "Keyboard",
            "Headset",
            "Gaming Gear",
            "Comset"
        };

        var existingCategoryNames = db.Categories
            .Select(c => c.Name)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        foreach (var categoryName in requiredCategories)
        {
            if (existingCategoryNames.Contains(categoryName))
            {
                continue;
            }

            db.Categories.Add(new Category
            {
                Name = categoryName
            });
        }

        db.SaveChanges();
    }

    // เติมสินค้าตัวอย่างพร้อมรูป placeholder ให้แคตตาล็อกเริ่มต้นใช้งานได้ทันที
    private static void SeedCatalogProducts(Csi402dbContext db)
    {
        var categories = db.Categories.ToList()
            .ToDictionary(c => c.Name, c => c, StringComparer.OrdinalIgnoreCase);

        var brands = db.Brands.ToList()
            .ToDictionary(b => b.BrandName, b => b, StringComparer.OrdinalIgnoreCase);

        var existingProducts = db.Products
            .Include(p => p.ProductImages)
            .ToList()
            .ToDictionary(p => p.Name, p => p, StringComparer.OrdinalIgnoreCase);

        foreach (var seed in GetCatalogProductSeeds())
        {
            if (!categories.TryGetValue(seed.CategoryName, out var category))
            {
                continue;
            }

            if (!brands.TryGetValue(seed.BrandName, out var brand))
            {
                brand = new Brand
                {
                    BrandName = seed.BrandName,
                    LogoUrl = null
                };

                db.Brands.Add(brand);
                db.SaveChanges();
                brands[seed.BrandName] = brand;
            }

            if (!existingProducts.TryGetValue(seed.Name, out var product))
            {
                product = new Product
                {
                    Name = seed.Name,
                    Description = seed.Description,
                    Price = seed.Price,
                    Stock = seed.Stock,
                    Sku = null,
                    CategoryId = category.CategoryId,
                    BrandId = brand.BrandId,
                    Status = "active",
                    CreatedAt = DateTime.Now
                };

                db.Products.Add(product);
                db.SaveChanges();

                db.ProductImages.Add(new ProductImage
                {
                    ProductId = product.ProductId,
                    ImageUrl = BuildPlaceholderImageUrl(seed.Name),
                    IsMain = true
                });

                db.SaveChanges();
                existingProducts[seed.Name] = product;
                continue;
            }

            var shouldUpdateProduct = false;

            if (string.IsNullOrWhiteSpace(product.Description))
            {
                product.Description = seed.Description;
                shouldUpdateProduct = true;
            }

            if ((product.Price <= 0) && seed.Price > 0)
            {
                product.Price = seed.Price;
                shouldUpdateProduct = true;
            }

            if ((product.Stock ?? 0) <= 0)
            {
                product.Stock = seed.Stock;
                shouldUpdateProduct = true;
            }

            if (!product.CategoryId.HasValue)
            {
                product.CategoryId = category.CategoryId;
                shouldUpdateProduct = true;
            }

            if (!product.BrandId.HasValue)
            {
                product.BrandId = brand.BrandId;
                shouldUpdateProduct = true;
            }

            if (string.IsNullOrWhiteSpace(product.Status))
            {
                product.Status = "active";
                shouldUpdateProduct = true;
            }

            if (shouldUpdateProduct)
            {
                db.Products.Update(product);
                db.SaveChanges();
            }

            if (!product.ProductImages.Any())
            {
                db.ProductImages.Add(new ProductImage
                {
                    ProductId = product.ProductId,
                    ImageUrl = BuildPlaceholderImageUrl(seed.Name),
                    IsMain = true
                });

                db.SaveChanges();
            }
        }
    }

    // เติม permission และสิทธิ์เริ่มต้นของ role ฝั่งหลังบ้าน
    private static void EnsureAuthorizationData(Csi402dbContext db)
    {
        var permissions = new[]
        {
            "dashboard.view",
            "products.manage",
            "stock.manage",
            "banners.manage",
            "promotions.manage",
            "brands.manage",
            "orders.view",
            "customers.manage",
            "admins.manage",
            "permissions.manage",
            "superadmin.dashboard"
        };

        var existingPermissions = db.Permissions
            .Where(p => p.PermissionName != null)
            .ToDictionary(p => p.PermissionName!, p => p, StringComparer.OrdinalIgnoreCase);

        foreach (var permissionName in permissions)
        {
            if (existingPermissions.ContainsKey(permissionName))
            {
                continue;
            }

            var permission = new Permission
            {
                PermissionName = permissionName
            };

            db.Permissions.Add(permission);
            db.SaveChanges();
            existingPermissions[permissionName] = permission;
        }

        var roles = db.Roles.ToDictionary(r => r.RoleName, r => r, StringComparer.OrdinalIgnoreCase);
        SeedRolePermissions(db, roles, existingPermissions, "admin", new[]
        {
            "dashboard.view",
            "products.manage",
            "stock.manage",
            "banners.manage",
            "promotions.manage",
            "brands.manage",
            "orders.view",
            "customers.manage"
        });

        SeedRolePermissions(db, roles, existingPermissions, "superadmin", permissions);
    }

    // เพิ่ม role-permission ที่ยังขาดให้ role เป้าหมายโดยไม่ซ้ำของเดิม
    private static void SeedRolePermissions(
        Csi402dbContext db,
        IReadOnlyDictionary<string, Role> roles,
        IReadOnlyDictionary<string, Permission> permissions,
        string roleName,
        IEnumerable<string> permissionNames)
    {
        if (!roles.TryGetValue(roleName, out var role))
        {
            return;
        }

        var existingPermissionIds = db.RolePermissions
            .Where(rp => rp.RoleId == role.RoleId && rp.PermissionId.HasValue)
            .Select(rp => rp.PermissionId!.Value)
            .ToHashSet();

        foreach (var permissionName in permissionNames)
        {
            if (!permissions.TryGetValue(permissionName, out var permission) || existingPermissionIds.Contains(permission.PermissionId))
            {
                continue;
            }

            db.RolePermissions.Add(new RolePermission
            {
                RoleId = role.RoleId,
                PermissionId = permission.PermissionId
            });
        }

        db.SaveChanges();
    }

    // สร้าง package ตัวอย่างของ Comset Starter Kit เมื่อยังไม่มี package item ในระบบ
    private static void EnsureComsetPackageSeed(Csi402dbContext db)
    {
        var packageProduct = db.Products.FirstOrDefault(p => p.Name == "Comset Starter Kit");
        if (packageProduct == null)
        {
            return;
        }

        var package = db.ProductPackages
            .Include(pp => pp.PackageItems)
            .FirstOrDefault(pp => pp.PackageId == packageProduct.ProductId || pp.Name == packageProduct.Name);

        if (package == null)
        {
            package = new ProductPackage
            {
                PackageId = packageProduct.ProductId,
                Name = packageProduct.Name,
                Price = packageProduct.Price
            };

            db.ProductPackages.Add(package);
            db.SaveChanges();
        }

        var hasPackageItems = db.PackageItems.Any(item => item.PackageId == package.PackageId);
        if (hasPackageItems)
        {
            return;
        }

        var componentIds = db.Products
            .Where(p => p.Name == "Keychron K6" || p.Name == "G Pro X Superlight" || p.Name == "HyperX Cloud II")
            .ToDictionary(p => p.Name, p => p.ProductId, StringComparer.OrdinalIgnoreCase);

        var packageItems = new List<PackageItem>();

        if (componentIds.TryGetValue("Keychron K6", out var keyboardId))
        {
            packageItems.Add(new PackageItem { PackageId = package.PackageId, ProductId = keyboardId, Quantity = 1 });
        }

        if (componentIds.TryGetValue("G Pro X Superlight", out var mouseId))
        {
            packageItems.Add(new PackageItem { PackageId = package.PackageId, ProductId = mouseId, Quantity = 1 });
        }

        if (componentIds.TryGetValue("HyperX Cloud II", out var headsetId))
        {
            packageItems.Add(new PackageItem { PackageId = package.PackageId, ProductId = headsetId, Quantity = 1 });
        }

        packageItems.Add(new PackageItem
        {
            PackageId = package.PackageId,
            ProductId = null,
            Quantity = 1
        });

        db.PackageItems.AddRange(packageItems);
        db.SaveChanges();
    }

    // ปรับ schema ของ promotions และ coupons ให้รองรับระบบคูปองยุคปัจจุบัน
    private static void EnsurePromotionCouponSchema(System.Data.Common.DbConnection connection)
    {
        if (!ColumnExists(connection, "promotions", "coupon_id"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE promotions ADD COLUMN coupon_id INT NULL AFTER promotion_id;");
        }

        if (!IndexExists(connection, "promotions", "idx_promotions_coupon_id"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE promotions ADD INDEX idx_promotions_coupon_id (coupon_id);");
        }

        if (!ForeignKeyExists(connection, "promotions", "fk_promotions_coupon"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE promotions ADD CONSTRAINT fk_promotions_coupon FOREIGN KEY (coupon_id) REFERENCES coupons (coupon_id);");
        }

        if (!ColumnExists(connection, "promotions", "minimum_order_subtotal"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE promotions ADD COLUMN minimum_order_subtotal DECIMAL(10,2) NULL AFTER coupon_id;");
        }

        if (!ColumnExists(connection, "coupons", "owner_user_id"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE coupons ADD COLUMN owner_user_id INT NULL AFTER coupon_id;");
        }

        if (!IndexExists(connection, "coupons", "idx_coupons_owner_user_id"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE coupons ADD INDEX idx_coupons_owner_user_id (owner_user_id);");
        }

        if (!ForeignKeyExists(connection, "coupons", "fk_coupons_owner_user"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE coupons ADD CONSTRAINT fk_coupons_owner_user FOREIGN KEY (owner_user_id) REFERENCES users (user_id);");
        }
    }

    // ปรับ schema ของ invite flow พร้อมย้ายข้อมูลเดิมให้รองรับ reward coupon และ invite code ถาวร
    private static void EnsureInvitePromotionSchema(System.Data.Common.DbConnection connection)
    {
        if (!ColumnExists(connection, "users", "invite_code"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE users ADD COLUMN invite_code VARCHAR(50) NULL AFTER email;");
        }

        if (!IndexExists(connection, "users", "uq_users_invite_code"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE users ADD UNIQUE INDEX uq_users_invite_code (invite_code);");
        }

        if (!ColumnExists(connection, "user_invites", "promotion_id"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE user_invites ADD COLUMN promotion_id INT NULL AFTER inviter_user_id;");
        }

        if (!ColumnExists(connection, "user_invites", "reward_coupon_id"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE user_invites ADD COLUMN reward_coupon_id INT NULL AFTER invited_user_id;");
        }

        if (!ColumnExists(connection, "user_invites", "rewarded_at"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE user_invites ADD COLUMN rewarded_at DATETIME NULL AFTER created_at;");
        }

        ExecuteNonQuery(connection, "ALTER TABLE user_invites MODIFY invited_email VARCHAR(100) NULL;");

        if (IndexExists(connection, "user_invites", "uq_user_invites_code"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE user_invites DROP INDEX uq_user_invites_code;");
        }

        if (!IndexExists(connection, "user_invites", "idx_user_invites_invite_code"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE user_invites ADD INDEX idx_user_invites_invite_code (invite_code);");
        }

        if (!IndexExists(connection, "user_invites", "idx_user_invites_promotion"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE user_invites ADD INDEX idx_user_invites_promotion (promotion_id);");
        }

        if (!IndexExists(connection, "user_invites", "idx_user_invites_reward_coupon"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE user_invites ADD INDEX idx_user_invites_reward_coupon (reward_coupon_id);");
        }

        if (!ForeignKeyExists(connection, "user_invites", "fk_user_invites_promotion"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE user_invites ADD CONSTRAINT fk_user_invites_promotion FOREIGN KEY (promotion_id) REFERENCES promotions (promotion_id);");
        }

        if (!ForeignKeyExists(connection, "user_invites", "fk_user_invites_reward_coupon"))
        {
            ExecuteNonQuery(connection, "ALTER TABLE user_invites ADD CONSTRAINT fk_user_invites_reward_coupon FOREIGN KEY (reward_coupon_id) REFERENCES coupons (coupon_id);");
        }

        ExecuteNonQuery(connection, @"
            UPDATE coupons c
            JOIN user_invites ui ON ui.reward_coupon_id = c.coupon_id
            SET c.owner_user_id = ui.inviter_user_id
            WHERE c.owner_user_id IS NULL;");

        ExecuteNonQuery(connection, @"
            UPDATE users u
            JOIN (
                SELECT inviter_user_id, MIN(invite_id) AS invite_id
                FROM user_invites
                WHERE invite_code IS NOT NULL AND invite_code <> ''
                GROUP BY inviter_user_id
            ) picked ON picked.inviter_user_id = u.user_id
            JOIN user_invites ui ON ui.invite_id = picked.invite_id
            SET u.invite_code = ui.invite_code
            WHERE (u.invite_code IS NULL OR u.invite_code = '')
              AND ui.invite_code IS NOT NULL
              AND ui.invite_code <> '';");
    }

    // สร้าง placeholder image URL จากชื่อสินค้าเมื่อยังไม่มีรูปจริง
    private static string BuildPlaceholderImageUrl(string productName)
    {
        return $"https://placehold.co/600x400?text={Uri.EscapeDataString(productName)}";
    }

    // คืนรายการ seed สินค้ามาตรฐานที่ใช้ populate แคตตาล็อกเริ่มต้น
    private static List<ProductSeed> GetCatalogProductSeeds()
    {
        return new List<ProductSeed>
        {
            new("RTX 4090", "Graphics Card", "NVIDIA", "การ์ดจอแรงสุดสำหรับ 4K / AI / Ray Tracing", 69990m, 4),
            new("RTX 4070 Super", "Graphics Card", "NVIDIA", "คุ้มค่า เล่นเกม 1440p-4K ได้ดี", 26990m, 8),
            new("RX 7900 XTX", "Graphics Card", "AMD", "ตัวแรงฝั่ง AMD VRAM เยอะ เหมาะงานกราฟิกหนัก", 35990m, 6),

            new("ASUS ROG Strix X670E-E", "Mainboard", "ASUS", "รองรับ AMD AM5 + PCIe 5.0", 16990m, 5),
            new("MSI B650 Tomahawk", "Mainboard", "MSI", "เมนบอร์ดกลางๆ คุ้มค่า", 8990m, 9),
            new("Gigabyte Z790 AORUS Elite", "Mainboard", "Gigabyte", "สำหรับ Intel Gen ใหม่ รองรับ OC", 10990m, 7),

            new("Corsair Vengeance DDR5 32GB", "RAM", "Corsair", "RAM ความเร็วสูง เหมาะ gaming + dev", 4290m, 14),
            new("G.Skill Trident Z5 RGB", "RAM", "G.Skill", "สาย RGB + OC", 4990m, 10),
            new("Kingston Fury Beast DDR5", "RAM", "Kingston", "ราคาคุ้ม ใช้งานทั่วไป", 2890m, 18),

            new("Samsung 990 Pro", "Storage", "Samsung", "SSD NVMe เร็วมาก ใช้ทำงาน/เกม", 5490m, 12),
            new("WD Black SN850X", "Storage", "Western Digital", "SSD สำหรับ gaming โหลดไว", 4990m, 11),
            new("Seagate Barracuda", "Storage", "Seagate", "HDD เก็บข้อมูลราคาถูก", 1990m, 20),

            new("Corsair RM850x", "Power Supply", "Corsair", "PSU Gold คุณภาพสูง เสถียร", 5290m, 8),
            new("Seasonic Focus GX-750", "Power Supply", "Seasonic", "แบรนด์ขึ้นชื่อเรื่องความทน", 4690m, 10),
            new("Cooler Master MWE Gold", "Power Supply", "Cooler Master", "ราคากลางๆ ใช้กับ gaming rig", 3490m, 13),

            new("NZXT Kraken X63", "Cooling", "NZXT", "ระบายความร้อนดี + RGB", 4990m, 7),
            new("Noctua NH-D15", "Cooling", "Noctua", "เงียบ + เย็นมาก", 3990m, 8),
            new("Hyper 212", "Cooling", "Cooler Master", "ถูกและคุ้ม", 1290m, 16),

            new("Lian Li PC-O11 Dynamic", "Case", "Lian Li", "สายโชว์ RGB / กระจก", 4690m, 7),
            new("NZXT H510", "Case", "NZXT", "Minimal design", 2590m, 12),
            new("Corsair 4000D Airflow", "Case", "Corsair", "airflow ดีมาก", 3290m, 10),

            new("LG UltraGear 27GP850", "Monitor", "LG", "1440p 165Hz สีสวย", 11990m, 9),
            new("ASUS TUF VG27AQ", "Monitor", "ASUS", "gaming คุ้มค่า", 9990m, 11),
            new("Samsung Odyssey G7", "Monitor", "Samsung", "โค้ง 240Hz", 15990m, 6),

            new("ROG Zephyrus G14", "Laptop", "ASUS", "บาง เบา แรง", 52990m, 4),
            new("Lenovo Legion 5", "Laptop", "Lenovo", "gaming คุ้มค่า", 42990m, 6),
            new("MSI Katana 15", "Laptop", "MSI", "ราคากลาง", 35990m, 7),

            new("G Pro X Superlight", "Mouse", "Logitech", "เบามาก esports", 3990m, 15),
            new("DeathAdder V3", "Mouse", "Razer", "จับถนัด", 2490m, 17),
            new("Rival 5", "Mouse", "SteelSeries", "multi-purpose", 1690m, 18),

            new("Keychron K6", "Keyboard", "Keychron", "mechanical + wireless", 2990m, 14),
            new("Corsair K70 RGB Pro", "Keyboard", "Corsair", "gaming + RGB", 4490m, 10),
            new("Razer Huntsman V2", "Keyboard", "Razer", "optical switch เร็ว", 4690m, 9),

            new("HyperX Cloud II", "Headset", "HyperX", "เสียงดี คุ้ม", 2490m, 16),
            new("Arctis 7", "Headset", "SteelSeries", "wireless", 3790m, 10),
            new("BlackShark V2", "Headset", "Razer", "esports", 2290m, 15),

            new("Elgato Stream Deck", "Gaming Gear", "Elgato", "ปุ่มลัดสำหรับสตรีมเมอร์", 4990m, 8),
            new("Razer Firefly", "Gaming Gear", "Razer", "mousepad RGB", 1690m, 14),
            new("Logitech G29", "Gaming Gear", "Logitech", "พวงมาลัยเกม", 8990m, 6),

            new("Comset Starter Kit", "Comset", "Logitech", "ชุดเริ่มต้นสำหรับคนอยากได้อุปกรณ์คอมเซ็ตพร้อมใช้งานในชุดเดียว", 8990m, 3)
        };
    }

    // โครงข้อมูลสั้น ๆ สำหรับเก็บรายละเอียด seed ของสินค้าแต่ละรายการ
    private sealed record ProductSeed(string Name, string CategoryName, string BrandName, string Description, decimal Price, int Stock);
}